name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Remplacez '3.x' par la version spécifique de Python que vous utilisez

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mvp_projet/requirements.txt

    - name: Run tests
      run: |
        cd mvp_projet