name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python "3.10"
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mvp_projet/requirements.txt

    - name: Set up PostgreSQL
      uses: ikalnytskyi/action-setup-postgres@v4
      with:
        username: 'test_user'
        password: 'test_password'
        database: 'test_db'

    - name: Set environment variables for testing
      run: |
        echo "DJANGO_DB_MODE=test" >> $GITHUB_ENV
        echo "POSTGRES_USER=test_user" >> $GITHUB_ENV
        echo "POSTGRES_PASSWORD=test_password" >> $GITHUB_ENV
        echo "POSTGRES_DB=test_db" >> $GITHUB_ENV
        echo "DATABASE_URL=postgres://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@localhost:5432/${{ env.POSTGRES_DB }}" >> $GITHUB_ENV

    - name: Apply migrations
      run: |
        cd mvp_projet
        python manage.py migrate

    - name: Print database configuration
      run: |
        cd mvp_projet
        python -c "import django; django.setup(); from django.conf import settings; print(settings.DATABASES)"

    - name: Collect static files
      run: |
        cd mvp_projet
        python manage.py collectstatic --noinput

    - name: Run tests
      run: |
        cd mvp_projet
        pytest