name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python "3.10"
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mvp_projet/requirements.txt

    - name: Set environment variables for testing
      run: |
        echo "DJANGO_DB_MODE=test" >> $GITHUB_ENV

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h postgres -p 5432; do
          echo "Waiting for PostgreSQL to become ready..."
          sleep 2
        done
        echo "PostgreSQL is ready!"

    - name: Apply migrations
      run: |
        cd mvp_projet
        python manage.py migrate

    - name: Print database configuration
      run: |
        cd mvp_projet
        python -c "from django.conf import settings; print(settings.DATABASES)"

    - name: Collect static files
      run: |
        cd mvp_projet
        python manage.py collectstatic --noinput

    - name: Run tests
      run: |
        cd mvp_projet
        pytest

    - name: Print PostgreSQL service logs (if failure)
      if: failure()
      run: |
        docker logs postgres